// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebMessagePojo.proto

package cn.com.papi.NettyClient.protobuf;

public final class WebMessagePojo {
  private WebMessagePojo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WebMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 ctrlType = 1;
    boolean hasCtrlType();
    int getCtrlType();
    
    // required string to = 2;
    boolean hasTo();
    String getTo();
    
    // required string data = 3;
    boolean hasData();
    String getData();
  }
  public static final class WebMessage extends
      com.google.protobuf.GeneratedMessage
      implements WebMessageOrBuilder {
    // Use WebMessage.newBuilder() to construct.
    private WebMessage(Builder builder) {
      super(builder);
    }
    private WebMessage(boolean noInit) {}
    
    private static final WebMessage defaultInstance;
    public static WebMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public WebMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.papi.NettyClient.protobuf.WebMessagePojo.internal_static_com_NettyClient_WebMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.papi.NettyClient.protobuf.WebMessagePojo.internal_static_com_NettyClient_WebMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 ctrlType = 1;
    public static final int CTRLTYPE_FIELD_NUMBER = 1;
    private int ctrlType_;
    public boolean hasCtrlType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCtrlType() {
      return ctrlType_;
    }
    
    // required string to = 2;
    public static final int TO_FIELD_NUMBER = 2;
    private java.lang.Object to_;
    public boolean hasTo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          to_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private java.lang.Object data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          data_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      ctrlType_ = 0;
      to_ = "";
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCtrlType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ctrlType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getToBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ctrlType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getToBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.com.papi.NettyClient.protobuf.WebMessagePojo.internal_static_com_NettyClient_WebMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.com.papi.NettyClient.protobuf.WebMessagePojo.internal_static_com_NettyClient_WebMessage_fieldAccessorTable;
      }
      
      // Construct using cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ctrlType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage.getDescriptor();
      }
      
      public cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage getDefaultInstanceForType() {
        return cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage.getDefaultInstance();
      }
      
      public cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage build() {
        cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage buildPartial() {
        cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage result = new cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ctrlType_ = ctrlType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage) {
          return mergeFrom((cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage other) {
        if (other == cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage.getDefaultInstance()) return this;
        if (other.hasCtrlType()) {
          setCtrlType(other.getCtrlType());
        }
        if (other.hasTo()) {
          setTo(other.getTo());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCtrlType()) {
          
          return false;
        }
        if (!hasTo()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ctrlType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              to_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 ctrlType = 1;
      private int ctrlType_ ;
      public boolean hasCtrlType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCtrlType() {
        return ctrlType_;
      }
      public Builder setCtrlType(int value) {
        bitField0_ |= 0x00000001;
        ctrlType_ = value;
        onChanged();
        return this;
      }
      public Builder clearCtrlType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ctrlType_ = 0;
        onChanged();
        return this;
      }
      
      // required string to = 2;
      private java.lang.Object to_ = "";
      public boolean hasTo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        to_ = value;
        onChanged();
        return this;
      }
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      void setTo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        to_ = value;
        onChanged();
      }
      
      // required string data = 3;
      private java.lang.Object data_ = "";
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setData(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      void setData(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:cn.com.papi.NettyClient.WebMessage)
    }
    
    static {
      defaultInstance = new WebMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.com.papi.NettyClient.WebMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_NettyClient_WebMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_NettyClient_WebMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024WebMessagePojo.proto\022\017cn.com.papi.NettyClient\"" +
      "8\n\nWebMessage\022\020\n\010ctrlType\030\001 \002(\005\022\n\n\002to\030\002 " +
      "\002(\t\022\014\n\004data\030\003 \002(\tB*\n\030cn.com.papi.NettyClient.pro" +
      "tobufB\016WebMessagePojo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_NettyClient_WebMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_NettyClient_WebMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_NettyClient_WebMessage_descriptor,
              new java.lang.String[] { "CtrlType", "To", "Data", },
              cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage.class,
              cn.com.papi.NettyClient.protobuf.WebMessagePojo.WebMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
